version: '3'
services:
  bcb:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
    ports:
      - 8082:8082
  erp-itau:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
    ports:
      - 9091:9091

  keymanager-rest:
    image: "gustavosantoszup/keymanager-rest"
    build:
      context: ../keymanager-rest
      dockerfile: ./Dockerfile
    environment:
      KEYMANAGER_GRPC_URL: keymanager-grpc:50051
      HEALTHCHECK_KEYMANAGER_HOST: keymanager-rest
      HEALTHCHECK_KEYMANAGER_PORT: 8080
      HEALTHCHECK_KEYMANAGER_ENDPOINT: check-grpc-status
      JAEGER_ENDPOINT: http://jaeger:14268/api/traces
      JAEGER_SAMPLE: 1
      JAEGER_ENABLED: 'true'
    ports:
      - 8080:8080
    depends_on:
      - keymanager-grpc
      - jaeger

  keymanager-grpc:
    image: "gustavosantoszup/keymanager-grpc"
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 50051:50051
    environment:
      ITAU_ERP_URL: http://erp-itau:9091
      BCB_URL: http://bcb:8082
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: keymanager
      DB_USERNAME: keymanager
      DB_PASSWORD: keymanager
    depends_on:
      - erp-itau
      - bcb
      - postgres

  postgres:
    image: 'postgres:alpine'
    volumes:
      - postgreskeymanager-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: keymanager
      POSTGRES_PASSWORD: keymanager
      POSTGRES_DB: keymanager
      POSTGRES_HOST: postgres

  prometheus:
    image: prom/prometheus
    volumes:
      - ../keymanager-rest/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheuskeymanager-volume:/etc/prometheus/
    network_mode: bridge
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - grafanakeymanager-volume:/var/lib/grafana
    network_mode: bridge
    ports:
      - "3000:3000"
    depends_on:
      - prometheus


  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

volumes:
  postgreskeymanager-volume:
  grafanakeymanager-volume:
  prometheuskeymanager-volume: